kmcmvc/Areas/Admin/Controllers/userinfoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using kmcmvc.Areas.Admin.Data;
using System.Linq.Dynamic;
using System.Data.Entity.Validation;

namespace kmcmvc.Areas.Admin.Controllers
{
    //[Authorize]
    public class userinfoesController : Controller
    {
        private AdminEntities db = new AdminEntities();

        // GET: Admin/userinfoes
        public ActionResult Index()
        {
            return View();
        }


        // POST: Admin/role
        [HttpPost]
        public JsonResult AjaxMethod()
        {
            using (AdminEntities entities = new AdminEntities())
            {
                List<role> roles = (from role in entities.roles
                                    select role).ToList();
                return Json(roles);
            }
        }

        // POST: Admin/userinfoes
        [HttpPost]
        public ActionResult GetList()
        {
            //Server Side Parameter
            int start = Convert.ToInt32(Request["start"]);
            int length = Convert.ToInt32(Request["length"]);
            string searchValue = Request.Form.GetValues("search[value]")[0];
            string sortColumnName = Request.Form.GetValues("columns[" +
            Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
            string sortDirection = Request["order[0][dir]"];

            List<userinfo> userinfoe = new List<userinfo>();
            int totalrecord = userinfoe.Count;
            using (AdminEntities db = new AdminEntities())
            {
                userinfoe = (from p in db.userinfoes
                             join f in db.roles
                        on p.RoleID equals f.RoleID
                             join a in db.accountstatus
                       on p.AccountStatusID equals a.AccountStatusID
                             where (p.FullName.ToLower() != null)
                             select new
                             {
                                 Id = p.userinfoID,
                                 Username = p.Username,
                                 FullName = p.FullName,
                                 status = a.AccountStatus,
                                 Rolename = f.RoleName
                             }).ToList()
                      .Select(x => new userinfo()
                      {
                          userinfoID = x.Id,
                          Username = x.Username,
                          FullName = x.FullName,
                          status = x.status,
                          Rolename = x.Rolename
                      }).ToList<userinfo>();

               // userinfoe = db.userinfoes.Where(x => x.FullName.ToLower() != null).ToList<userinfo>();

                if (!string.IsNullOrEmpty(searchValue))
                {
                    userinfoe = userinfoe.
                        Where(x => x.Username.ToLower().Contains(searchValue.ToLower()) || x.FullName.ToLower().Contains(searchValue.ToLower()) || x.Rolename.Contains(searchValue.ToLower()) || x.status.Contains(searchValue.ToLower())).ToList<userinfo>();
                }
                int totalrowsafterfiltering = userinfoe.Count;
                // sorting
                userinfoe = userinfoe.OrderBy(sortColumnName + " " + sortDirection).ToList<userinfo>();


                // pagination
                userinfoe = userinfoe.Skip(start).Take(length).ToList<userinfo>();

                return Json(new { data = userinfoe, draw = Request["draw"], recordsTotal = totalrecord, recordsFiltered = totalrowsafterfiltering }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Admin/userinfoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            var userinfolist = (from p in db.userinfoes
                            join f in db.roles
                       on p.RoleID equals f.RoleID
                            join a in db.accountstatus
                       on p.AccountStatusID equals a.AccountStatusID
                           where (p.userinfoID == id)
                           select new
                           {
                               Id = p.userinfoID,
                               Username = p.Username,
                               FullName = p.FullName,
                               Password = p.Password,
                               Mobile = p.Mobile,
                               Email = p.Email,
                               CNIC = p.CNIC,
                               Address = p.Address,
                               status = a.AccountStatus,
                               Rolename = f.RoleName
                           }).ToList()
                    .Select(x => new userinfo()
                    {
                        userinfoID = x.Id,
                        Username = x.Username,
                        FullName = x.FullName,
                        Password = x.Password,
                        Mobile = x.Mobile,
                        Email = x.Email,
                        CNIC = x.CNIC,
                        Address = x.Address,
                        status = x.status,
                        Rolename = x.Rolename
                    }).SingleOrDefault();



            //userinfo userinfo = db.userinfoes.Find(id);
            if (userinfolist == null)
            {
                return HttpNotFound();
            }
            return View(userinfolist);
        }



        // GET: Admin/userinfoes/Create
        [AllowAnonymous]
        [HttpGet]
        public ActionResult Create()
        {
            userinfo u = new userinfo();
            u.rolelist = db.roles.ToList();
            u.statuslist = db.accountstatus.Where(x => x.AccountStatus == "Active" || x.AccountStatus == "De-Active" || x.AccountStatus == "Suspended").ToList();
            u.status = "";
            u.Rolename = "";
            return View(u);
        }

        // POST: Admin/userinfoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "userinfoID,Username,FullName,Password,Mobile,Email,CNIC,Address,RoleID,AccountStatusID")] userinfo userinfo)
        {
            if (!ModelState.IsValid)
            {
                db.userinfoes.Add(userinfo);
                //db.Entry(userinfo).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else if (ModelState.IsValid)
            {
                db.userinfoes.Add(userinfo);
                db.Entry(userinfo).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userinfo);
        }

        // GET: Admin/userinfoes/Edit/5
        public ActionResult Edit(int? id)
        {
            userinfo userinfo = new userinfo();
            userinfo = db.userinfoes.Find(id);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            userinfo.rolelist = db.roles.ToList();
            userinfo.statuslist = db.accountstatus.Where(x => x.AccountStatus == "Active" || x.AccountStatus == "De-Active" || x.AccountStatus == "Suspended").ToList();
            userinfo.status = "";
            userinfo.Rolename = "";
            
            if (userinfo == null)
            {
                return HttpNotFound();
            }
            return View(userinfo);
        }

        // POST: Admin/userinfoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "userinfoID,Username,FullName,Password,Mobile,Email,CNIC,Address,RoleID,AccountStatusID")] userinfo userinfo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userinfo).State = EntityState.Modified;
               
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userinfo);
        }

        // GET: Admin/userinfoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            userinfo userinfo = db.userinfoes.Find(id);
            if (userinfo == null)
            {
                return HttpNotFound();
            }
            return View(userinfo);
        }

        // POST: Admin/userinfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            userinfo userinfo = db.userinfoes.Find(id);
            db.userinfoes.Remove(userinfo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

kmcmvc/Areas/Admin/Views/userinfoes/Create.cshtml
@model kmcmvc.Areas.Admin.Data.userinfo


@{
    ViewBag.Title = "Add User Info";
}


@using (Html.BeginForm("Create", "userinfoes", FormMethod.Post, new { id = "main" }))
{
    @Html.AntiForgeryToken()
    

    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper">
                <!-- Page body start -->
                <div class="page-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <!-- Basic Inputs Validation start -->
                            <div class="card">
                                <div class="card-header">
                                    <h5>Add MUCT User Info</h5>
                                    @*<span>Add town of <code>.form-control</code> with <code>&lt;input&gt;</code> tag</span>*@
                                    
                                    @Html.ValidationSummary(true, "", new { @class = "messages" })
                                </div>
                                <div class="card-block">
                                    @*<form id="main" method="post" action="/" novalidate>*@
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">User Name</label>
                                            <div class="col-sm-10">
                                                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" }})
                                                @*@Html.ValidationMessageFor(model => model.Username, "", new { @class = "messages" })*@
                                                <span class="messages"></span>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">Full Name</label>
                                            <div class="col-sm-10">
                                                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "messages" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">Password</label>
                                            <div class="col-sm-10">
                                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "messages" })
                                                <span class="messages"></span>
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">Mobile</label>
                                            <div class="col-sm-10">
                                                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "messages" })
                                                <span class="messages"></span>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">Email</label>
                                            <div class="col-sm-10">
                                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "messages" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">CNIC</label>
                                            <div class="col-sm-10">
                                                @Html.EditorFor(model => model.CNIC, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.CNIC, "", new { @class = "messages" })
                                                <span class="messages"></span>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">Address</label>
                                            <div class="col-sm-10">
                                                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "messages" })
                                                <span class="messages"></span>
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">Roles</label>
                                            <div class="col-sm-10">
                                                <h4 class="sub-title">Select Role For An Account</h4>
                                                <div class="form-radio">
                                                    <div class="radio radio-outline radio-inline">
                                                        @foreach (var ML in Model.rolelist)
                                                        {
                                                            <div class="radio radio-outline radio-inline">
                                                                <label>
                                                                    @Html.RadioButton("RoleID", ML.RoleID, new { @class = "radio" })<i class="helper"></i> @ML.RoleName
                                                                    @Html.ValidationMessageFor(model => model.RoleID, "", new { @class = "text-danger" })
                                                                </label>
                                                            </div>

                                                        }
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">Status</label>
                                            <div class="col-sm-10">
                                                <h4 class="sub-title">Select Status For An Account</h4>
                                                <div class="form-radio">
                                                    <div class="radio radio-outline radio-inline">
                                                        @foreach (var ML in Model.statuslist)
                                                        {
                                                            <div class="radio radio-outline radio-inline">
                                                                <label>
                                                                    @Html.RadioButton("AccountStatusID", ML.AccountStatusID, new { @class = "radio" })<i class="helper"></i> @ML.AccountStatus
                                                                </label>
                                                            </div>

                                                        }
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label class="col-sm-2"></label>

                                            <div class="col-sm-10">
                                                <button type="submit" class="btn waves-effect waves-light btn-success btn-outline-success"><i class="icofont icofont-check-circled"></i>Submit</button>
                                            </div>
                                        </div>

                                    @*</form>*@
                                </div>
                               
                            </div>
                               
                            
                            <!-- Basic Inputs Validation end -->
                            <div class="card-block tooltip-icon button-list">
                                <p>Use following button <code>according to your needs.</code></p>
                                <a type="button" href="/Admin/userinfoes/Index" class="btn btn-primary btn-icon waves-effect waves-light" data-toggle="tooltip" data-placement="left" title="Back To Dashboard">
                                    <i class="icofont icofont-home"></i>
                                </a>
                                <a type="button" href="/Admin/userinfoes/Index" class="btn btn-success btn-icon waves-effect waves-light" data-toggle="tooltip" data-placement="bottom" title="Back To Users List">
                                    <i class="icofont icofont-paper-plane"></i>
                                </a>
                                <a type="button" class="btn btn-danger btn-icon waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="Back To Profile">
                                    <i class="icofont icofont-boy"></i>
                                </a>
                                <a type="button" class="btn btn-warning btn-icon waves-effect waves-light" data-toggle="tooltip" data-placement="right" title="Logout">
                                    <i class="icofont icofont-logout"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Page body end -->
            </div>
        </div>
    </div>

}

kmcmvc/Areas/Admin/Views/userinfoes/Delete.cshtml
@model kmcmvc.Areas.Admin.Data.userinfo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>userinfo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CNIC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CNIC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoleID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoleID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountStatusID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountStatusID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

kmcmvc/Areas/Admin/Views/userinfoes/Details.cshtml
@model kmcmvc.Areas.Admin.Data.userinfo

@{
    ViewBag.Title = "Details";
}

<div class="pcoded-inner-content">
    <!-- Main-body start -->
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Page-body start -->
            <div class="page-body">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h5>Details of Selected Users</h5>
                                <span>
                                    <p>Use following button <code>according to your needs.</code></p>

                                    <a type="button" class="btn waves-effect waves-dark btn-primary btn-outline-primary btn-icon" href="/Admin/userinfoes/Edit/@Model.userinfoID" data-toggle="tooltip" data-placement="bottom" title="Edit"><i class="icofont icofont-ui-edit"></i></a>

                                    <a type="button" href="/Admin/userinfoes/Index" class="btn waves-effect waves-dark btn-primary btn-outline-success btn-icon" data-toggle="tooltip" data-placement="bottom" title="Back To Users List">
                                        <i class="icofont icofont-paper-plane"></i>
                                    </a>

                                </span>
                            </div>
                            <div class="card-block">
                                @*<p>
                                    While Bootstrap uses <code class="highlighter-rouge">em</code>s or <code class="highlighter-rouge">rem</code>s for defining most sizes, <code class="highlighter-rouge">px</code>s are used for grid
                                    breakpoints and container widths. This is because the viewport width is in pixels and does not change with the <a href="https://drafts.csswg.org/mediaqueries-3/#units">font size</a>.
                                </p>
                                <p>See how aspects of the Bootstrap grid system work across multiple devices with a handy table.</p>*@
                                <div class="table-responsive">
                                    <table class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>Details Parameters</th>
                                                <th class="text-center">
                                                    @Html.DisplayFor(model => model.Username)
                                                    <br>
                                                    <small>&lt;Details></small>
                                                </th>
                                               
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <th class="text-nowrap" scope="row">Username</th>
                                                <td>@Html.DisplayFor(model => model.Username)</td>
                                            </tr>
                                            <tr>
                                                <th class="text-nowrap" scope="row">Full Name</th>
                                                <td>@Html.DisplayFor(model => model.FullName)</td>
                                            </tr>
                                            <tr>
                                                <th class="text-nowrap" scope="row">Password</th>
                                                <td><code>@Html.DisplayFor(model => model.Password)</code></td>
                                            </tr>
                                            <tr>
                                                <th class="text-nowrap" scope="row">Mobile</th>
                                                <td colspan="5">@Html.DisplayFor(model => model.Mobile)</td>
                                            </tr>
                                            <tr>
                                                <th class="text-nowrap" scope="row">Email</th>
                                                <td colspan="5">@Html.DisplayFor(model => model.Email)</td>
                                            </tr>
                                            <tr>
                                                <th class="text-nowrap" scope="row">CNIC</th>
                                                <td colspan="5">@Html.DisplayFor(model => model.CNIC)</td>
                                            </tr>
                                            <tr>
                                                <th class="text-nowrap" scope="row">Address</th>
                                                <td colspan="5">@Html.DisplayFor(model => model.Address)</td>
                                            </tr>
                                            <tr>
                                                <th class="text-nowrap" scope="row">Roles</th>
                                                <td colspan="5">@Html.DisplayFor(model => model.Rolename)</td>
                                            </tr>
                                            <tr>
                                                <th class="text-nowrap" scope="row">Status</th>
                                                <td colspan="5">@Html.DisplayFor(model => model.status)</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>